#修改PRODUCT: K2P_nano 中的K2P_nano为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'   
env:
  #源码库选择
  REPO_URL: https://github.com/padavanonly/rt-n56u.git
  #REPO_URL: https://github.com/hanwckf/rt-n56u.git
  REPO_BRANCH: master
  #编译设备型号K2P-USB,K2P
  PRODUCT: K2P_nano

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin

    - name: Clone source code
      run: |
        git clone --depth=1 $REPO_URL -b $REPO_BRANCH /opt/rt-n56u
        
    - name: toolchain
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
        
    - name: Build Firmware
      run: |
        echo "BUILD_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        cd /opt/rt-n56u/trunk
        fakeroot ./build_firmware_modify $PRODUCT
        sudo mv -f images/*.trx /opt/images/${{ env.PRODUCT }}-${{ env.BUILD_DATE }}.trx
        
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-${{ env.PRODUCT }}-${{ env.BUILD_DATE }}
        path: /opt/images
